services:
  resfs:
    build: .
    ports:
      - "8787:8787"
    environment:
      - DOPPLER_TOKEN
      - PASSWORD
      - SMB_USER
      - SMB_PASS
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    entrypoint: ["/bin/bash", "-c", "doppler run -- /bin/bash -c '/setup_scripts/install_whisper.sh && /usr/local/bin/mount.sh && exec /init'"]
    volumes:
      - /mnt/datasets:/mnt/datasets
      - /mnt/projects:/mnt/projects
      - /var/run/docker.sock:/var/run/docker.sock
    
    